name = "worker"
main = "src/index.ts"
compatibility_date = "2023-05-19"

[placement]
mode = "smart"

[[r2_buckets]]
binding = 'JOBCOMPASS_BUCKET'
bucket_name = 'jobcompass'
preview_bucket_name = 'jobcompass-staging'